name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Switch to nightly
      run: rustup default nightly
    - name: Build
      run: cargo build --verbose
    - name: Run criterion tests
      run: cargo bench
    - name: Install cargo-insta
      run: cargo install cargo-insta
    - name: Generate cargo insta snapshots
      run: cargo insta test
